# Generated by Django 4.2.15 on 2024-09-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_note_status_note_user_id_alter_note_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Imege'),
        ),
        migrations.AddField(
            model_name='note',
            name='user_tg_id',
            field=models.IntegerField(null=True, verbose_name='Tg User ID'),
        ),
    ]
